TRUNCATE TABLE public.ranked_songs RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.excluded_songs RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.songs RESTART IDENTITY CASCADE;

INSERT INTO public.songs (title, game, artist, youtube_video_id, thumbnail_url, release_year) VALUES
('Overworld Theme', 'Super Mario Bros', 'Koji Kondo', 'iy3qq7zc4EY', 'https://img.youtube.com/vi/iy3qq7zc4EY/maxresdefault.jpg', 1985),
('Underground Theme', 'Super Mario Bros', 'Koji Kondo', 'c0SuIMUoShI', 'https://img.youtube.com/vi/c0SuIMUoShI/maxresdefault.jpg', 1985),
('Athletic Theme', 'Super Mario Bros 3', 'Koji Kondo', 'EODf7xKDih0', 'https://img.youtube.com/vi/EODf7xKDih0/maxresdefault.jpg', 1988),
('Castle Theme', 'Super Mario Bros', 'Koji Kondo', 'I9TFZbC27aw', 'https://img.youtube.com/vi/I9TFZbC27aw/maxresdefault.jpg', 1985),
('Starman Theme', 'Super Mario Bros', 'Koji Kondo', 'xjSyzDqSi7Q', 'https://img.youtube.com/vi/xjSyzDqSi7Q/maxresdefault.jpg', 1985),
('Game Over', 'Super Mario Bros', 'Koji Kondo', 'mav6BXbQQJg', 'https://img.youtube.com/vi/mav6BXbQQJg/maxresdefault.jpg', 1985),
('World Clear', 'Super Mario Bros', 'Koji Kondo', '83baaBCYzyI', 'https://img.youtube.com/vi/83baaBCYzyI/maxresdefault.jpg', 1985),
('Overworld Theme', 'Super Mario Bros 2', 'Daisuke Matsuoka', 'yBISfv-6hfo', 'https://img.youtube.com/vi/yBISfv-6hfo/maxresdefault.jpg', 1988),
('Underground Theme', 'Super Mario Bros 2', 'Daisuke Matsuoka', 'B6-DrbE4LfY', 'https://img.youtube.com/vi/B6-DrbE4LfY/maxresdefault.jpg', 1988),
('Boss Battle', 'Super Mario Bros 2', 'Daisuke Matsuoka', '1gQOprzFxxQ', 'https://img.youtube.com/vi/1gQOprzFxxQ/maxresdefault.jpg', 1988),
('Character Select', 'Super Mario Bros 2', 'Daisuke Matsuoka', 'Mdnnfg6Yvb0', 'https://img.youtube.com/vi/Mdnnfg6Yvb0/maxresdefault.jpg', 1988),
('Ending Theme', 'Super Mario Bros 2', 'Daisuke Matsuoka', '9GB8SSIK0sQ', 'https://img.youtube.com/vi/9GB8SSIK0sQ/maxresdefault.jpg', 1988),
('Overworld 1', 'Super Mario Bros 3', 'Koji Kondo', '1yfxp1NhLIs', 'https://img.youtube.com/vi/1yfxp1NhLIs/maxresdefault.jpg', 1988),
('Underground Theme', 'Super Mario Bros 3', 'Koji Kondo', 'decbYrsCjOk', 'https://img.youtube.com/vi/decbYrsCjOk/maxresdefault.jpg', 1988),
('Underwater Theme', 'Super Mario Bros 3', 'Koji Kondo', 'B7D0GKJDU3I', 'https://img.youtube.com/vi/B7D0GKJDU3I/maxresdefault.jpg', 1988),
('Fortress Boss', 'Super Mario Bros 3', 'Koji Kondo', 'xGr_BSMe6xw', 'https://img.youtube.com/vi/xGr_BSMe6xw/maxresdefault.jpg', 1988),
('Sky Land Theme', 'Super Mario Bros 3', 'Koji Kondo', 'h7YMomQ6pFA', 'https://img.youtube.com/vi/h7YMomQ6pFA/maxresdefault.jpg', 1988),
('World Map Theme', 'Super Mario Bros Wonder', 'Koji Kondo', 'dFi-E4q0Ulg', 'https://img.youtube.com/vi/dFi-E4q0Ulg/maxresdefault.jpg', 2023),
('Ending Theme', 'Super Mario Bros 3', 'Koji Kondo', 'GzN-6zYmdAw', 'https://img.youtube.com/vi/GzN-6zYmdAw/maxresdefault.jpg', 1988),
('Overworld Theme (Sarasaland)', 'Super Mario Land', 'Hirokazu Tanaka', 'ZexyCYXoYHM', 'https://img.youtube.com/vi/ZexyCYXoYHM/maxresdefault.jpg', 1989),
('Underground Theme', 'Super Mario Land', 'Hirokazu Tanaka', 'DnKoJSqFcNg', 'https://img.youtube.com/vi/DnKoJSqFcNg/maxresdefault.jpg', 1989),
('Boss Battle', 'Super Mario Land', 'Hirokazu Tanaka', 'U8k5OyxoR5o', 'https://img.youtube.com/vi/U8k5OyxoR5o/maxresdefault.jpg', 1989),
('Wonder Flower Transformation', 'Super Mario Bros Wonder', 'Koji Kondo', 'J93TA8BTVgo', 'https://img.youtube.com/vi/J93TA8BTVgo/maxresdefault.jpg', 2023),
('Ghost House', 'Super Mario 3D Land', 'Koji Kondo', 'FfbKXYbgFfw', 'https://img.youtube.com/vi/FfbKXYbgFfw/maxresdefault.jpg', 2011),
('Forest of Illusion', 'Super Mario World', 'Koji Kondo', 'iclRx9wdx78', 'https://img.youtube.com/vi/iclRx9wdx78/maxresdefault.jpg', 1990),
('Sunshine Airport', 'Mario Kart 8', 'Various', 'bSX2aoAn_u0', 'https://img.youtube.com/vi/bSX2aoAn_u0/maxresdefault.jpg', 2014),
('Great Tower Showdown 2', 'Super Mario 3D World', 'Koji Kondo', 'uBy7J9ZuL-Y', 'https://img.youtube.com/vi/uBy7J9ZuL-Y/maxresdefault.jpg', 2013),
('Star Road', 'Super Mario World', 'Koji Kondo', 'oRM6SGqvIHg', 'https://img.youtube.com/vi/oRM6SGqvIHg/maxresdefault.jpg', 1990),
('Ending Theme', 'Super Mario World', 'Koji Kondo', 'gNcIAC30mWI', 'https://img.youtube.com/vi/gNcIAC30mWI/maxresdefault.jpg', 1990),
('Vanilla Dome', 'Super Mario World', 'Koji Kondo', '5jjkYX6-mXY', 'https://img.youtube.com/vi/5jjkYX6-mXY/maxresdefault.jpg', 1990),
('Overworld Theme', 'Super Mario Land 2', 'Ryoji Yoshitomi', '6lhbYWbPmkE', 'https://img.youtube.com/vi/6lhbYWbPmkE/maxresdefault.jpg', 1992),
('Wario''s Castle', 'Super Mario Land 2', 'Ryoji Yoshitomi', 'bt4Irs2qobU', 'https://img.youtube.com/vi/bt4Irs2qobU/maxresdefault.jpg', 1992),
('Space Zone', 'Super Mario Land 2', 'Ryoji Yoshitomi', 'T26cuCzF6_Y', 'https://img.youtube.com/vi/T26cuCzF6_Y/maxresdefault.jpg', 1992),
('Let''s Try!', 'Super Mario RPG', 'Yoko Shimomura', 'ywSnE-PMKsM', 'https://img.youtube.com/vi/ywSnE-PMKsM/maxresdefault.jpg', 1996),
('Forest Maze', 'Super Mario RPG', 'Yoko Shimomura', '3TeQ7jFDwF0', 'https://img.youtube.com/vi/3TeQ7jFDwF0/maxresdefault.jpg', 1996),
('Fight Against a Stronger Monster', 'Super Mario RPG', 'Yoko Shimomura', '913OrSdDFf0', 'https://img.youtube.com/vi/913OrSdDFf0/maxresdefault.jpg', 1996),
('Shogun Studios', 'Paper Mario: The Origami King', 'Yasunori Mitsuda', 'atfF77M4msI', 'https://img.youtube.com/vi/atfF77M4msI/maxresdefault.jpg', 2020),
('File Select', 'Super Mario 64', 'Koji Kondo', 'PcLPwqG1KLI', 'https://img.youtube.com/vi/PcLPwqG1KLI/maxresdefault.jpg', 1996),
('Bob-omb Battlefield', 'Super Mario 64', 'Koji Kondo', 'bmP3UHXYi28', 'https://img.youtube.com/vi/bmP3UHXYi28/maxresdefault.jpg', 1996),
('Dire, Dire Docks', 'Super Mario 64', 'Koji Kondo', '89-f5qcJVng', 'https://img.youtube.com/vi/89-f5qcJVng/maxresdefault.jpg', 1996),
('Cool, Cool Mountain', 'Super Mario 64', 'Koji Kondo', 'zzxHzfvA1sI', 'https://img.youtube.com/vi/zzxHzfvA1sI/maxresdefault.jpg', 1996),
('Koopa''s Road', 'Super Mario 64', 'Koji Kondo', '_eZNlyGhYFo', 'https://img.youtube.com/vi/_eZNlyGhYFo/maxresdefault.jpg', 1996),
('Bowser''s Road', 'Super Mario 64', 'Koji Kondo', 'eM5nOBgpDsQ', 'https://img.youtube.com/vi/eM5nOBgpDsQ/maxresdefault.jpg', 1996),
('Inside the Castle Walls', 'Super Mario 64', 'Koji Kondo', '-pdLR-nsvlY', 'https://img.youtube.com/vi/-pdLR-nsvlY/maxresdefault.jpg', 1996),
('King Kaliente', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', '79KpN8ZvOec', 'https://img.youtube.com/vi/79KpN8ZvOec/maxresdefault.jpg', 2007),
('Honeyhive Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', 'scCgiF9tGb0', 'https://img.youtube.com/vi/scCgiF9tGb0/maxresdefault.jpg', 2007),
('Snowman''s Land', 'Super Mario 64', 'Koji Kondo', '6mtTT4_Kaao', 'https://img.youtube.com/vi/6mtTT4_Kaao/maxresdefault.jpg', 1996),
('Slide Theme', 'Super Mario 64', 'Koji Kondo', 'DKXBYZJlDFM', 'https://img.youtube.com/vi/DKXBYZJlDFM/maxresdefault.jpg', 1996),
('Piranha Plant''s Lullaby', 'Super Mario 64', 'Koji Kondo', '4xqFVWqM-k4', 'https://img.youtube.com/vi/4xqFVWqM-k4/maxresdefault.jpg', 1996),
('Battlerock Galaxy (Wii)', 'Super Mario Galaxy', 'Mahito Yokota', '73iWfOMWFM4', 'https://img.youtube.com/vi/73iWfOMWFM4/maxresdefault.jpg', 2007),
('Main Theme', 'Mario Kart 64', 'Kenta Nagata', 'Qxn3g9qbF3Q', 'https://img.youtube.com/vi/Qxn3g9qbF3Q/maxresdefault.jpg', 1996),
('Mario Raceway', 'Mario Kart 64', 'Kenta Nagata', '9ZQ62vEjgjE', 'https://img.youtube.com/vi/9ZQ62vEjgjE/maxresdefault.jpg', 1996),
('Rainbow Road', 'Mario Kart 64', 'Kenta Nagata', 'K5xdue7GFcc', 'https://img.youtube.com/vi/K5xdue7GFcc/maxresdefault.jpg', 1996),
('Koopa Troopa Beach', 'Mario Kart 64', 'Kenta Nagata', 'WGFAPl2uu28', 'https://img.youtube.com/vi/WGFAPl2uu28/maxresdefault.jpg', 1996),
('Luma', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', '9chsn7yWKPo', 'https://img.youtube.com/vi/9chsn7yWKPo/maxresdefault.jpg', 2007),
('Title Theme', 'Paper Mario', 'Yoko Shimomura', 'eH1a-QQhFdk', 'https://img.youtube.com/vi/eH1a-QQhFdk/maxresdefault.jpg', 2000),
('Koopa Village', 'Paper Mario', 'Yoko Shimomura', 'UMW9frJBwH8', 'https://img.youtube.com/vi/UMW9frJBwH8/maxresdefault.jpg', 2000),
('Battle Theme', 'Paper Mario: The Origami King', 'Yasunori Mitsuda', 'ALxd2CitF5k', 'https://img.youtube.com/vi/ALxd2CitF5k/maxresdefault.jpg', 2020),
('X-Nauts Fortress', 'Paper Mario: TTYD', 'Yoko Shimomura', 'bMrJHK2LNzc', 'https://img.youtube.com/vi/bMrJHK2LNzc/maxresdefault.jpg', 2004),
('Mute City', 'Mario Kart 8', 'Various', '9zyPO2hF8_o', 'https://img.youtube.com/vi/9zyPO2hF8_o/maxresdefault.jpg', 2014),
('Delfino Plaza', 'Super Mario Sunshine', 'Koji Kondo', '48vYjsfu1Uc', 'https://img.youtube.com/vi/48vYjsfu1Uc/maxresdefault.jpg', 2002),
('Ricco Harbor', 'Super Mario Sunshine', 'Koji Kondo', '-JpjTsxZwFk', 'https://img.youtube.com/vi/-JpjTsxZwFk/maxresdefault.jpg', 2002),
('Bianco Hills', 'Super Mario Sunshine', 'Koji Kondo', 'AEY8tfNtu7U', 'https://img.youtube.com/vi/AEY8tfNtu7U/maxresdefault.jpg', 2002),
('Pinna Park Beach', 'Super Mario Sunshine', 'Koji Kondo', '4dekvtChpdI', 'https://img.youtube.com/vi/4dekvtChpdI/maxresdefault.jpg', 2002),
('Boss Battle (Petey Piranha)', 'Super Mario Sunshine', 'Koji Kondo', '2XJ7e2CyI1w', 'https://img.youtube.com/vi/2XJ7e2CyI1w/maxresdefault.jpg', 2002),
('Corona Mountain', 'Super Mario Sunshine', 'Koji Kondo', 'sUpzC0DPTHE', 'https://img.youtube.com/vi/sUpzC0DPTHE/maxresdefault.jpg', 2002),
('Luigi Circuit', 'Mario Kart: Double Dash!!', 'Kenta Nagata', 'XcjD_44jL1Y', 'https://img.youtube.com/vi/XcjD_44jL1Y/maxresdefault.jpg', 2003),
('Baby Park', 'Mario Kart: Double Dash!!', 'Kenta Nagata', 'fmnlHkcLcl0', 'https://img.youtube.com/vi/fmnlHkcLcl0/maxresdefault.jpg', 2003),
('Rainbow Road', 'Mario Kart Wii', 'Kota Hoshino', 'BjjNdkFGrPI', 'https://img.youtube.com/vi/BjjNdkFGrPI/maxresdefault.jpg', 2008),
('Mario Circuit', 'Mario Kart 8 Deluxe', 'Various', 'M-xzowm5Vf0', 'https://img.youtube.com/vi/M-xzowm5Vf0/maxresdefault.jpg', 2014),
('Doopliss Battle', 'Paper Mario TTYD', 'Various', 'r2y7DMIGvkY', 'https://img.youtube.com/vi/r2y7DMIGvkY/maxresdefault.jpg', 2004),
('The Glitz Pit', 'Paper Mario: TTYD', 'Yoko Shimomura', 'baULW_hg2Po', 'https://img.youtube.com/vi/baULW_hg2Po/maxresdefault.jpg', 2004),
('Main Theme', 'New Super Mario Bros', 'Asuka Ohta', 'YOxqgLUPFHg', 'https://img.youtube.com/vi/YOxqgLUPFHg/maxresdefault.jpg', 2006),
('Boss Battle', 'New Super Mario Bros Wii', 'Koji Kondo', 'VAEVdji1dA8', 'https://img.youtube.com/vi/VAEVdji1dA8/maxresdefault.jpg', 2009),
('Boss Battle', 'New Super Mario Bros', 'Asuka Ohta', 'vn9SHJaar3I', 'https://img.youtube.com/vi/vn9SHJaar3I/maxresdefault.jpg', 2006),
('Overture', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', 'qv1aIZMAgH8', 'https://img.youtube.com/vi/qv1aIZMAgH8/maxresdefault.jpg', 2007),
('Good Egg Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', '56TfZJoZxv8', 'https://img.youtube.com/vi/56TfZJoZxv8/maxresdefault.jpg', 2007),
('Comet Observatory', 'Super Mario Galaxy', 'Mahito Yokota', 'wBhzmys2-eU', 'https://img.youtube.com/vi/wBhzmys2-eU/maxresdefault.jpg', 2007),
('Buoy Base Galaxy', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', 'SmUn_YgOBAw', 'https://img.youtube.com/vi/SmUn_YgOBAw/maxresdefault.jpg', 2007),
('Gusty Garden Galaxy', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', 'Rrx0F1TzQ0M', 'https://img.youtube.com/vi/Rrx0F1TzQ0M/maxresdefault.jpg', 2007),
('Freezeflame Galaxy', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', 'BpndWW2NyDs', 'https://img.youtube.com/vi/BpndWW2NyDs/maxresdefault.jpg', 2007),
('Bowser''s Fortresses', 'Super Mario Galaxy 2', 'Mahito Yokota / Ryo Nagamatsu', '9zBawgVbOaA', 'https://img.youtube.com/vi/9zBawgVbOaA/maxresdefault.jpg', 2010),
('Bowser Battle', 'Super Mario Odyssey', 'Naoki Sakatoku', 'VrDBsoen0Ng', 'https://img.youtube.com/vi/VrDBsoen0Ng/maxresdefault.jpg', 2017),
('Star Festival', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', 'mt1rrOo4m6k', 'https://img.youtube.com/vi/mt1rrOo4m6k/maxresdefault.jpg', 2007),
('Main Theme', 'Mario Kart Wii', 'Kota Hoshino', 'BB8skjdBPDc', 'https://img.youtube.com/vi/BB8skjdBPDc/maxresdefault.jpg', 2008),
('Coconut Mall', 'Mario Kart Wii', 'Kota Hoshino', 'cscuCIzItZQ', 'https://img.youtube.com/vi/cscuCIzItZQ/maxresdefault.jpg', 2008),
('Main Theme', 'Mario Kart 8 Deluxe', 'Various', 'YWkbfwTN46Y', 'https://img.youtube.com/vi/YWkbfwTN46Y/maxresdefault.jpg', 2014),
('Athletic Theme', 'New Super Mario Bros Wii', 'Various', '64de5MbyQZU', 'https://img.youtube.com/vi/64de5MbyQZU/maxresdefault.jpg', 2009),
('Airship Theme', 'New Super Mario Bros Wii', 'Koji Kondo', 'ZCf57aOTdXU', 'https://img.youtube.com/vi/ZCf57aOTdXU/maxresdefault.jpg', 2009),
('Sky Station Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', 'Y5uGrLUr_3g', 'https://img.youtube.com/vi/Y5uGrLUr_3g/maxresdefault.jpg', 2010),
('Flip-Swap Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', 'X0ceqgw3PUQ', 'https://img.youtube.com/vi/X0ceqgw3PUQ/maxresdefault.jpg', 2010),
('Puzzle Plank', 'Super Mario Galaxy 2', 'Mahito Yokota', '4sJijxXt_d4', 'https://img.youtube.com/vi/4sJijxXt_d4/maxresdefault.jpg', 2010),
('Main Theme (3DL)', 'Super Mario 3D Land', 'Various', '-fEt-Ax11vI', 'https://img.youtube.com/vi/-fEt-Ax11vI/maxresdefault.jpg', 2011),
('Mount Must Dash', 'Super Mario 3D World', 'Various', '-Pgj1XfTiHI', 'https://img.youtube.com/vi/-Pgj1XfTiHI/maxresdefault.jpg', 2013),
('Rainbow Road', 'Mario Kart 8 Deluxe', 'Ryo Nagamatsu', 'ksDFjM_5r_s', 'https://img.youtube.com/vi/ksDFjM_5r_s/maxresdefault.jpg', 2014),
('Bone Dry Dunes', 'Mario Kart 8 Deluxe', 'Various', '2xEiDABY61s', 'https://img.youtube.com/vi/2xEiDABY61s/maxresdefault.jpg', 2014),
('Sweet Sweet Canyon', 'Mario Kart 8 Deluxe', 'Various', 'xSgCIFd8uOw', 'https://img.youtube.com/vi/xSgCIFd8uOw/maxresdefault.jpg', 2014),
('Overworld Theme', 'New Super Mario Bros U', 'Shinobu Tanaka', 'P-nWggWYkw0', 'https://img.youtube.com/vi/P-nWggWYkw0/maxresdefault.jpg', 2012),
('Acorn Plains Way', 'New Super Mario Bros U', 'Shinobu Tanaka', '3z7t5ht8JOg', 'https://img.youtube.com/vi/3z7t5ht8JOg/maxresdefault.jpg', 2012),
('Super Bell Hill', 'Super Mario 3D World', 'Various', 'FPXAW-wVHp8', 'https://img.youtube.com/vi/FPXAW-wVHp8/maxresdefault.jpg', 2013),
('World Bowser', 'Super Mario 3D World', 'Various', 'YAYLJ19cxoA', 'https://img.youtube.com/vi/YAYLJ19cxoA/maxresdefault.jpg', 2013),
('Toad Harbor', 'Mario Kart 8', 'Various', 'F1-pwhFgDdo', 'https://img.youtube.com/vi/F1-pwhFgDdo/maxresdefault.jpg', 2014),
('Mount Wario', 'Mario Kart 8 Deluxe', 'Various', 'R1fZFQrxgdc', 'https://img.youtube.com/vi/R1fZFQrxgdc/maxresdefault.jpg', 2014),
('Electrodrome', 'Mario Kart 8', 'Various', 'wHKD9jhqZfM', 'https://img.youtube.com/vi/wHKD9jhqZfM/maxresdefault.jpg', 2014),
('Cloudtop Cruise', 'Mario Kart 8', 'Various', '4MKuBwQSU3o', 'https://img.youtube.com/vi/4MKuBwQSU3o/maxresdefault.jpg', 2014),
('Water Park', 'Mario Kart 8 Deluxe', 'Various', '4jQhuZvdho0', 'https://img.youtube.com/vi/4jQhuZvdho0/maxresdefault.jpg', 2014),
('Shy Guy Falls', 'Mario Kart 8 Deluxe', 'Various', 'kWlIlLg5o6c', 'https://img.youtube.com/vi/kWlIlLg5o6c/maxresdefault.jpg', 2014),
('Mount Volbono', 'Super Mario Odyssey', 'Naoki Sakatoku', 'vy3PSN1g3T0', 'https://img.youtube.com/vi/vy3PSN1g3T0/maxresdefault.jpg', 2017),
('Tostarena (Night)', 'Super Mario Odyssey', 'Naoki Sakatoku', 'BdphGjFITLs', 'https://img.youtube.com/vi/BdphGjFITLs/maxresdefault.jpg', 2017),
('Luncheon Kingdom', 'Super Mario Odyssey', 'Naoki Sakatoku', 'cnF0SaU3N-E', 'https://img.youtube.com/vi/cnF0SaU3N-E/maxresdefault.jpg', 2017),
('Sand Kingdom (Tostarena)', 'Super Mario Odyssey', 'Naoki Sakatoku', 'vkrbKejaSSE', 'https://img.youtube.com/vi/vkrbKejaSSE/maxresdefault.jpg', 2017),
('Bonneton (Cap Kingdom)', 'Super Mario Odyssey', 'Naoki Sakatoku', 'wVGqg4rBRbg', 'https://img.youtube.com/vi/wVGqg4rBRbg/maxresdefault.jpg', 2017),
('Honeylune Ridge (Escape)', 'Super Mario Odyssey', 'Naoki Sakatoku', 'DNXTxZVZ4UQ', 'https://img.youtube.com/vi/DNXTxZVZ4UQ/maxresdefault.jpg', 2017),
('Fossil Falls (Cascade Kingdom)', 'Super Mario Odyssey', 'Naoki Sakatoku', 'jR8BJNVwbnI', 'https://img.youtube.com/vi/jR8BJNVwbnI/maxresdefault.jpg', 2017),
('Bubblaine', 'Super Mario Odyssey', 'Naoki Sakatoku', 'll_4VLuPvRk', 'https://img.youtube.com/vi/ll_4VLuPvRk/maxresdefault.jpg', 2017),
('Cloud Kingdom', 'Super Mario Odyssey', 'Naoki Sakatoku', '80ZYToHHWZc', 'https://img.youtube.com/vi/80ZYToHHWZc/maxresdefault.jpg', 2017),
('Snow Kingdom', 'Super Mario Odyssey', 'Naoki Sakatoku', '9fTUeU2oIlA', 'https://img.youtube.com/vi/9fTUeU2oIlA/maxresdefault.jpg', 2017),
('Seaside Kingdom', 'Super Mario Odyssey', 'Naoki Sakatoku', 'VhAyXM7Z1Jg', 'https://img.youtube.com/vi/VhAyXM7Z1Jg/maxresdefault.jpg', 2017),
('Top-Hat Tower', 'Super Mario Odyssey', 'Naoki Sakatoku', 'RD8iCp1Eo_k', 'https://img.youtube.com/vi/RD8iCp1Eo_k/maxresdefault.jpg', 2017),
('Mushroom Kingdom', 'Super Mario Odyssey', 'Naoki Sakatoku', '2Utqotx0XvI', 'https://img.youtube.com/vi/2Utqotx0XvI/maxresdefault.jpg', 2017),
('The Darker Side', 'Super Mario Odyssey', 'Naoki Sakatoku', 'mThUv9V3IbE', 'https://img.youtube.com/vi/mThUv9V3IbE/maxresdefault.jpg', 2017),
('Western Land', 'Mario Party 2', 'Shiho Fujii', 'l9cfpn81pyA', 'https://img.youtube.com/vi/l9cfpn81pyA/maxresdefault.jpg', 1999),
('Horror Land', 'Mario Party 2', 'Shiho Fujii', 'fRZq6lX1Exk', 'https://img.youtube.com/vi/fRZq6lX1Exk/maxresdefault.jpg', 1999),
('Waluigi''s Island', 'Mario Party 3', 'Shiho Fujii', 'NMcuHxQ2zAY', 'https://img.youtube.com/vi/NMcuHxQ2zAY/maxresdefault.jpg', 2000),
('Boo''s Haunted Bash', 'Mario Party 4', 'Shinobu Tanaka', 'cf5QEsVddjk', 'https://img.youtube.com/vi/cf5QEsVddjk/maxresdefault.jpg', 2002),
('Toad''s Midway Madness', 'Mario Party 4', 'Shinobu Tanaka', 'DsIWVz-YyGQ', 'https://img.youtube.com/vi/DsIWVz-YyGQ/maxresdefault.jpg', 2002),
('Toy Dream', 'Mario Party 5', 'Shinobu Tanaka', 'jUTWm8lAH7U', 'https://img.youtube.com/vi/jUTWm8lAH7U/maxresdefault.jpg', 2003),
('Future Dream', 'Mario Party 5', 'Shinobu Tanaka', 'jf6ZEO_iQIs', 'https://img.youtube.com/vi/jf6ZEO_iQIs/maxresdefault.jpg', 2003),
('Overworld Theme', 'Yoshi''s Island', 'Koji Kondo', 'tQfDGANrYDw', 'https://img.youtube.com/vi/tQfDGANrYDw/maxresdefault.jpg', 1995),
('Athletic Theme', 'Yoshi''s Island', 'Koji Kondo', 'oKJ2EZnnZRE', 'https://img.youtube.com/vi/oKJ2EZnnZRE/maxresdefault.jpg', 1995),
('Boss Battle', 'Yoshi''s Island', 'Koji Kondo', 'HEFvJCfiN-Q', 'https://img.youtube.com/vi/HEFvJCfiN-Q/maxresdefault.jpg', 1995),
('Castle & Fortress', 'Yoshi''s Island', 'Koji Kondo', '34uh4AMthsU', 'https://img.youtube.com/vi/34uh4AMthsU/maxresdefault.jpg', 1995),
('Baby Bowser''s Lullaby', 'Yoshi''s Island', 'Koji Kondo', 'aDO9r3211BQ', 'https://img.youtube.com/vi/aDO9r3211BQ/maxresdefault.jpg', 1995),
('Yoshi''s Story Theme', 'Yoshi''s Story', 'Kazumi Totaka', 'nghTrcPBp3s', 'https://img.youtube.com/vi/nghTrcPBp3s/maxresdefault.jpg', 1997),
('Ending Theme', 'Yoshi''s Story', 'Kazumi Totaka', 'fwq0CdFfEJA', 'https://img.youtube.com/vi/fwq0CdFfEJA/maxresdefault.jpg', 1997),
('World Maker Theme', 'Super Mario Maker 2', 'Koji Kondo', 'hs8RJRTnuyQ', 'https://img.youtube.com/vi/hs8RJRTnuyQ/maxresdefault.jpg', 2019),
('Super Mario 3D World Style', 'Super Mario Maker 2', 'Koji Kondo', '_xC0uTUp_6s', 'https://img.youtube.com/vi/_xC0uTUp_6s/maxresdefault.jpg', 2019),
('Prisma Fountain', 'Paper Mario: Color Splash', 'Yuka Tsujiyoko', 'pSZJtMdyqYg', 'https://img.youtube.com/vi/pSZJtMdyqYg/maxresdefault.jpg', 2016),
('The Emerald Circus', 'Paper Mario: Color Splash', 'Yuka Tsujiyoko', 'hTLU50TMO8s', 'https://img.youtube.com/vi/hTLU50TMO8s/maxresdefault.jpg', 2016),
('Combat! (Battle Theme)', 'Paper Mario: Color Splash', 'Yuka Tsujiyoko', 'hpJ5fLn34Kc', 'https://img.youtube.com/vi/hpJ5fLn34Kc/maxresdefault.jpg', 2016),
('Ground Theme (Alternative)', 'Super Mario Bros', 'Koji Kondo', 'f7Kkf7aPvD4', 'https://img.youtube.com/vi/f7Kkf7aPvD4/maxresdefault.jpg', 1985),
('Main Theme', 'Mario Golf', 'Motoi Sakuraba', 'Dft1j19x-Sg', 'https://img.youtube.com/vi/Dft1j19x-Sg/maxresdefault.jpg', 1999),
('Main Theme', 'Mario Tennis', 'Motoi Sakuraba', 'JovYzCAVUys', 'https://img.youtube.com/vi/JovYzCAVUys/maxresdefault.jpg', 2000),
('Main Theme', 'Mario Strikers Charged', 'Various', 'bcl0rA1ueiI', 'https://img.youtube.com/vi/bcl0rA1ueiI/maxresdefault.jpg', 2007),
('King Bob-omb''s Powderkeg Mine', 'Super Mario Party', 'Various', 'Kvf2bu7jzBg', 'https://img.youtube.com/vi/Kvf2bu7jzBg/maxresdefault.jpg', 2018),
('Kamek''s Library', 'Super Mario Party', 'Various', 'QgpmrSKzVOA', 'https://img.youtube.com/vi/QgpmrSKzVOA/maxresdefault.jpg', 2018),
('Paris Promenade', 'Mario Kart 8 Deluxe BCP', 'Various', 'sxldcPwQSNM', 'https://img.youtube.com/vi/sxldcPwQSNM/maxresdefault.jpg', 2022),
('Mushroom Gorge', 'Mario Kart 8 Deluxe BCP', 'Various', 'OL_5IKFde3o', 'https://img.youtube.com/vi/OL_5IKFde3o/maxresdefault.jpg', 2022),
('Sky-High Sundae', 'Mario Kart 8 Deluxe BCP', 'Various', 'OaPJFWG-2ak', 'https://img.youtube.com/vi/OaPJFWG-2ak/maxresdefault.jpg', 2022),
('Main Theme (Remix)', 'Super Mario 64 DS', 'Koji Kondo', 'rISqk65a_Hg', 'https://img.youtube.com/vi/rISqk65a_Hg/maxresdefault.jpg', 2004),
('Overworld Theme (Remix)', 'Super Mario Advance', 'Koji Kondo', 'B8qHxZd7e8w', 'https://img.youtube.com/vi/B8qHxZd7e8w/maxresdefault.jpg', 2001),
('Main Theme', 'Mario Party Superstars', 'Various', 'ZehHFXRjUEU', 'https://img.youtube.com/vi/ZehHFXRjUEU/maxresdefault.jpg', 2021),
('Peach''s Birthday Cake', 'Mario Party Superstars', 'Various', 'l9xPLr5WWvA', 'https://img.youtube.com/vi/l9xPLr5WWvA/maxresdefault.jpg', 2021),
('Yoshi''s Tropical Island', 'Mario Party Superstars', 'Various', 'g68oLCJ7RZs', 'https://img.youtube.com/vi/g68oLCJ7RZs/maxresdefault.jpg', 2021),
('Overworld Theme', 'Super Mario Bros: The Lost Levels', 'Koji Kondo', 'EnKyo-LKK4k', 'https://img.youtube.com/vi/EnKyo-LKK4k/maxresdefault.jpg', 1986),
('Koopa Cape', 'Mario Kart Wii', 'Asuka Ohta', 'G89au61guSE', 'https://img.youtube.com/vi/G89au61guSE/maxresdefault.jpg', 2008),
('Mushroom Gorge', 'Mario Kart Wii', 'Asuka Ohta', 'oz5pYtTCdgU', 'https://img.youtube.com/vi/oz5pYtTCdgU/maxresdefault.jpg', 2008),
('Daisy Circuit', 'Mario Kart Wii', 'Kota Hoshino', 'thSVBWx-tBo', 'https://img.youtube.com/vi/thSVBWx-tBo/maxresdefault.jpg', 2008),
('Anti-Gravity Highway', 'Mario Kart 8 Deluxe', 'Various', 'dmRczb17ygU', 'https://img.youtube.com/vi/dmRczb17ygU/maxresdefault.jpg', 2014),
('Hyrule Circuit', 'Mario Kart 8', 'Various', 'oh-Fp0L5R3Y', 'https://img.youtube.com/vi/oh-Fp0L5R3Y/maxresdefault.jpg', 2014),
('Animal Crossing', 'Mario Kart 8', 'Various', 'HAQpiSX-8LI', 'https://img.youtube.com/vi/HAQpiSX-8LI/maxresdefault.jpg', 2014),
('Lost Kingdom', 'Super Mario Odyssey', 'Naoki Sakatoku', '-5iYS5YnxIo', 'https://img.youtube.com/vi/-5iYS5YnxIo/maxresdefault.jpg', 2017),
('Bowser''s Wedding (Culmina Crater)', 'Super Mario Odyssey', 'Naoki Sakatoku', '8rbRYsv4jY4', 'https://img.youtube.com/vi/8rbRYsv4jY4/maxresdefault.jpg', 2017),
('Space Junk (Dusty Dune Galaxy)', 'Super Mario Galaxy', 'Koji Kondo / Mahito Yokota', 'NQT2WX6syrU', 'https://img.youtube.com/vi/NQT2WX6syrU/maxresdefault.jpg', 2007),
('Beach Bowl Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', 'w4WR84qeQHE', 'https://img.youtube.com/vi/w4WR84qeQHE/maxresdefault.jpg', 2007),
('Toy Time Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', '0EzhcY10f_E', 'https://img.youtube.com/vi/0EzhcY10f_E/maxresdefault.jpg', 2007),
('Melty Molten Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', 'gr-X7-VapTI', 'https://img.youtube.com/vi/gr-X7-VapTI/maxresdefault.jpg', 2007),
('Cloudy Court Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota / Ryo Nagamatsu', 'A0UuXdh1j7Q', 'https://img.youtube.com/vi/A0UuXdh1j7Q/maxresdefault.jpg', 2010),
('Rightside Down Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota / Ryo Nagamatsu', 'SACrxYPC-N0', 'https://img.youtube.com/vi/SACrxYPC-N0/maxresdefault.jpg', 2010),
('The Great Tree', 'Paper Mario: TTYD', 'Yoko Shimomura', 'NKiWqG3A5fg', 'https://img.youtube.com/vi/NKiWqG3A5fg/maxresdefault.jpg', 2004),
('Twilight Town', 'Paper Mario: TTYD', 'Yoko Shimomura', 'hAIjnyUn_DI', 'https://img.youtube.com/vi/hAIjnyUn_DI/maxresdefault.jpg', 2004),
('Petal Meadows', 'Paper Mario: TTYD', 'Yoko Shimomura', 'dzdTQrzWS_M', 'https://img.youtube.com/vi/dzdTQrzWS_M/maxresdefault.jpg', 2004),
('Shadow Queen Battle', 'Paper Mario: TTYD', 'Yoko Shimomura', 'tgV1ycMTv60', 'https://img.youtube.com/vi/tgV1ycMTv60/maxresdefault.jpg', 2004),
('Beware the Forest''s Mushrooms (Remake)', 'Super Mario RPG Remake', 'Yoko Shimomura', '5dN3JCsGFTY', 'https://img.youtube.com/vi/5dN3JCsGFTY/maxresdefault.jpg', 2023),
('Booster Tower (Remake)', 'Super Mario RPG Remake', 'Yoko Shimomura', 'ofKb-v1-OB8', 'https://img.youtube.com/vi/ofKb-v1-OB8/maxresdefault.jpg', 2023),
('Jump Up, Super Star!', 'Super Mario Odyssey', 'Naoki Sakatoku', 'e9r5hx47kxM', 'https://img.youtube.com/vi/e9r5hx47kxM/maxresdefault.jpg', 2017),
('Waluigi Pinball', 'Mario Kart DS', 'Shinobu Tanaka', 'lsIJMVg4c1w', 'https://img.youtube.com/vi/lsIJMVg4c1w/maxresdefault.jpg', 2005),
('Piranha Plants on Parade', 'Super Mario Bros Wonder', 'Koji Kondo', 'UzsJQnC_UTw', 'https://img.youtube.com/vi/UzsJQnC_UTw/maxresdefault.jpg', 2023),
('Rainbow Road', 'Mario Kart 7', 'Kenta Nagata', '082eZvnVD7M', 'https://img.youtube.com/vi/082eZvnVD7M/maxresdefault.jpg', 2011),
('Neo Bowser City', 'Mario Kart 7', 'Kenta Nagata', 'fxsPY5GYaFE', 'https://img.youtube.com/vi/fxsPY5GYaFE/maxresdefault.jpg', 2011),
('Maple Treeway', 'Mario Kart Wii', 'Asuka Ohta', 'i08-uym7o5c', 'https://img.youtube.com/vi/i08-uym7o5c/maxresdefault.jpg', 2008),
('Delfino Square', 'Mario Kart DS', 'Shinobu Tanaka', 'LiqvDbuP63o', 'https://img.youtube.com/vi/LiqvDbuP63o/maxresdefault.jpg', 2005),
('Airship Fortress', 'Mario Kart DS', 'Shinobu Tanaka', 'sUlKXP2XozE', 'https://img.youtube.com/vi/sUlKXP2XozE/maxresdefault.jpg', 2005),
('New Donk City (Day)', 'Super Mario Odyssey', 'Naoki Sakatoku', 'Pd0CCCmI7sw', 'https://img.youtube.com/vi/Pd0CCCmI7sw/maxresdefault.jpg', 2017),
('Egg Planet', 'Super Mario Galaxy', 'Mahito Yokota', 'XsYlK-ZxcmM', 'https://img.youtube.com/vi/XsYlK-ZxcmM/maxresdefault.jpg', 2007),
('Space Junk Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', 'tBruJYZgkMk', 'https://img.youtube.com/vi/tBruJYZgkMk/maxresdefault.jpg', 2007),
('Bowser Battle', 'Super Mario Galaxy', 'Mahito Yokota', '1_VZo01MWYo', 'https://img.youtube.com/vi/1_VZo01MWYo/maxresdefault.jpg', 2007),
('Staff Credits', 'Super Mario Galaxy', 'Mahito Yokota', 'VlA_BMPb0aE', 'https://img.youtube.com/vi/VlA_BMPb0aE/maxresdefault.jpg', 2007),
('Bowser Final Battle', 'Super Mario Galaxy 2', 'Mahito Yokota', 'FckLwjiPMKg', 'https://img.youtube.com/vi/FckLwjiPMKg/maxresdefault.jpg', 2010),
('World Map', 'Super Mario Galaxy 2', 'Mahito Yokota', 'fAgv21_u12c', 'https://img.youtube.com/vi/fAgv21_u12c/maxresdefault.jpg', 2010),
('Cosmic Cove Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', 'zcV7RptHqro', 'https://img.youtube.com/vi/zcV7RptHqro/maxresdefault.jpg', 2010),
('Staff Roll', 'Super Mario 64', 'Koji Kondo', 'o-xRxXYpavU', 'https://img.youtube.com/vi/o-xRxXYpavU/maxresdefault.jpg', 1996),
('Lethal Lava Land', 'Super Mario 64', 'Koji Kondo', 'vthq62tj5XI', 'https://img.youtube.com/vi/vthq62tj5XI/maxresdefault.jpg', 1996),
('Overworld Theme', 'New Super Mario Bros Wii', 'Various', 'R6eF5g_NTvE', 'https://img.youtube.com/vi/R6eF5g_NTvE/maxresdefault.jpg', 2009),
('Castle Theme', 'New Super Mario Bros Wii', 'Various', '7S3s_60QKVU', 'https://img.youtube.com/vi/7S3s_60QKVU/maxresdefault.jpg', 2009),
('Final Boss', 'New Super Mario Bros Wii', 'Various', 'QkGhHr6aa2U', 'https://img.youtube.com/vi/QkGhHr6aa2U/maxresdefault.jpg', 2009),
('Athletic Theme', 'New Super Mario Bros DS', 'Various', 'P-c_mnqz8Bg', 'https://img.youtube.com/vi/P-c_mnqz8Bg/maxresdefault.jpg', 2006),
('Rainbow Road', 'Mario Kart DS', 'Shinobu Tanaka', 'qyYTvaxzAi0', 'https://img.youtube.com/vi/qyYTvaxzAi0/maxresdefault.jpg', 2005),
('Main Menu', 'Mario Kart DS', 'Shinobu Tanaka', 'wdJ-CNPV0Jc', 'https://img.youtube.com/vi/wdJ-CNPV0Jc/maxresdefault.jpg', 2005),
('Koopa Beach', 'Mario Kart 64', 'Kenta Nagata', 'IuApZnHpu4A', 'https://img.youtube.com/vi/IuApZnHpu4A/maxresdefault.jpg', 1996),
('Rainbow Road', 'Mario Kart Double Dash', 'Various', '54-1Y-KIhjY', 'https://img.youtube.com/vi/54-1Y-KIhjY/maxresdefault.jpg', 2003),
('Lake Lamode', 'Super Mario Odyssey', 'Naoki Sakatoku', 'sEzjreOPzzs', 'https://img.youtube.com/vi/sEzjreOPzzs/maxresdefault.jpg', 2017),
('Bowser Battle 1', 'Super Mario Odyssey', 'Naoki Sakatoku', '5gYjPD1LIe0', 'https://img.youtube.com/vi/5gYjPD1LIe0/maxresdefault.jpg', 2017),
('Secret Course', 'Super Mario Sunshine', 'Koji Kondo', '5E9svMa42lw', 'https://img.youtube.com/vi/5E9svMa42lw/maxresdefault.jpg', 2002),
('Champion''s Road', 'Super Mario 3D World', 'Mahito Yokota', 'hm18WGZynbQ', 'https://img.youtube.com/vi/hm18WGZynbQ/maxresdefault.jpg', 2013),
('World Star', 'Super Mario 3D World', 'Mahito Yokota', 'Fnd_I4o7vkk', 'https://img.youtube.com/vi/Fnd_I4o7vkk/maxresdefault.jpg', 2013),
('Rosalina in the Observatory 1', 'Super Mario Galaxy', 'Mahito Yokota', 'cM2Gp9r1oeI', 'https://img.youtube.com/vi/cM2Gp9r1oeI/maxresdefault.jpg', 2007),
('Rosalina in the Observatory 2', 'Super Mario Galaxy', 'Mahito Yokota', 'Y0U5_UslDSg', 'https://img.youtube.com/vi/Y0U5_UslDSg/maxresdefault.jpg', 2007),
('Gateway Galaxy', 'Super Mario Galaxy', 'Mahito Yokota', 'k3ut6ATtOx0', 'https://img.youtube.com/vi/k3ut6ATtOx0/maxresdefault.jpg', 2007),
('Bowser Jr Airship Armada', 'Super Mario Galaxy', 'Mahito Yokota', 'hph7xClOiXY', 'https://img.youtube.com/vi/hph7xClOiXY/maxresdefault.jpg', 2007),
('King Kaliente Battle', 'Super Mario Galaxy', 'Mahito Yokota', 'f6URd5C9TBQ', 'https://img.youtube.com/vi/f6URd5C9TBQ/maxresdefault.jpg', 2007),
('Purple Comet', 'Super Mario Galaxy', 'Mahito Yokota', 'WDvNuNv7lDQ', 'https://img.youtube.com/vi/WDvNuNv7lDQ/maxresdefault.jpg', 2007),
('Final Bowser Battle', 'Super Mario Galaxy', 'Mahito Yokota', 'c4XbbGtbuZg', 'https://img.youtube.com/vi/c4XbbGtbuZg/maxresdefault.jpg', 2007),
('Waltz of the Boos', 'Super Mario Galaxy', 'Mahito Yokota', 'gef0XD45FsI', 'https://img.youtube.com/vi/gef0XD45FsI/maxresdefault.jpg', 2007),
('Starship Mario', 'Super Mario Galaxy 2', 'Mahito Yokota', 'La4SaT461WI', 'https://img.youtube.com/vi/La4SaT461WI/maxresdefault.jpg', 2010),
('Throwback Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', '2VUOS4wACFE', 'https://img.youtube.com/vi/2VUOS4wACFE/maxresdefault.jpg', 2010),
('Boo Moon Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', 'TTSCPOekHM4', 'https://img.youtube.com/vi/TTSCPOekHM4/maxresdefault.jpg', 2010),
('Wild Glide Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', 'tQZn0a-P-qU', 'https://img.youtube.com/vi/tQZn0a-P-qU/maxresdefault.jpg', 2010),
('World S', 'Super Mario Galaxy 2', 'Mahito Yokota', '3rUpNSONNYo', 'https://img.youtube.com/vi/3rUpNSONNYo/maxresdefault.jpg', 2010),
('Fluffy Bluff Galaxy', 'Super Mario Galaxy 2', 'Mahito Yokota', 'CHD2MDciu6Y', 'https://img.youtube.com/vi/CHD2MDciu6Y/maxresdefault.jpg', 2010),
('Staff Credits', 'Super Mario Galaxy 2', 'Mahito Yokota', 'VWmtUJxdcW8', 'https://img.youtube.com/vi/VWmtUJxdcW8/maxresdefault.jpg', 2010),
('Piranha Plant Lullaby', 'Super Mario 64', 'Koji Kondo', 'ujmCQzbhTUw', 'https://img.youtube.com/vi/ujmCQzbhTUw/maxresdefault.jpg', 1996),
('Bowser Road', 'Super Mario 64', 'Koji Kondo', 'AJj6GGLaIfI', 'https://img.youtube.com/vi/AJj6GGLaIfI/maxresdefault.jpg', 1996),
('Ultimate Bowser', 'Super Mario 64', 'Koji Kondo', 'rnC1jOqpSlg', 'https://img.youtube.com/vi/rnC1jOqpSlg/maxresdefault.jpg', 1996),
('Wing Cap', 'Super Mario 64', 'Koji Kondo', 'WGxvGgbHUAE', 'https://img.youtube.com/vi/WGxvGgbHUAE/maxresdefault.jpg', 1996),
('Metal Cap', 'Super Mario 64', 'Koji Kondo', 'YTn2sViERsg', 'https://img.youtube.com/vi/YTn2sViERsg/maxresdefault.jpg', 1996),
('Final Boss', 'New Super Mario Bros DS', 'Various', 'gO7VKT-I8Po', 'https://img.youtube.com/vi/gO7VKT-I8Po/maxresdefault.jpg', 2006),
('Castle Theme', 'New Super Mario Bros DS', 'Various', '3oPHiQq0KTk', 'https://img.youtube.com/vi/3oPHiQq0KTk/maxresdefault.jpg', 2006),
('Beach Theme', 'New Super Mario Bros DS', 'Various', 'Gv_Uw59VNvo', 'https://img.youtube.com/vi/Gv_Uw59VNvo/maxresdefault.jpg', 2006),
('Underground Theme', 'New Super Mario Bros Wii', 'Various', '2hY9wDzd8Wk', 'https://img.youtube.com/vi/2hY9wDzd8Wk/maxresdefault.jpg', 2009),
('World Map', 'New Super Mario Bros Wii', 'Various', 'NsmYGlJ-eBE', 'https://img.youtube.com/vi/NsmYGlJ-eBE/maxresdefault.jpg', 2009),
('Acorn Plains', 'New Super Mario Bros U', 'Various', 'Ll2Vm9jVOoA', 'https://img.youtube.com/vi/Ll2Vm9jVOoA/maxresdefault.jpg', 2012),
('Menu Theme', 'Super Smash Bros Melee', 'Hirokazu Ando', 'C9jJfwwRdrU', 'https://img.youtube.com/vi/C9jJfwwRdrU/maxresdefault.jpg', 2001),
('Opening', 'Super Smash Bros Melee', 'Hirokazu Ando', 'Damxx4K_Yo8', 'https://img.youtube.com/vi/Damxx4K_Yo8/maxresdefault.jpg', 2001),
('Final Destination', 'Super Smash Bros Melee', 'Hirokazu Ando', '3Z5Sgc3_ZD8', 'https://img.youtube.com/vi/3Z5Sgc3_ZD8/maxresdefault.jpg', 2001),
('Battlefield', 'Super Smash Bros Melee', 'Hirokazu Ando', 'yjdgpFgW1T0', 'https://img.youtube.com/vi/yjdgpFgW1T0/maxresdefault.jpg', 2001),
('Menu Theme', 'Super Smash Bros Brawl', 'Nobuo Uematsu', 'kSUr2CXB29c', 'https://img.youtube.com/vi/kSUr2CXB29c/maxresdefault.jpg', 2008),
('Final Destination', 'Super Smash Bros Brawl', 'Nobuo Uematsu', '52i7DhGWO8Q', 'https://img.youtube.com/vi/52i7DhGWO8Q/maxresdefault.jpg', 2008),
('Main Theme', 'Super Smash Bros Brawl', 'Nobuo Uematsu', 'zeKE0NHUtUw', 'https://img.youtube.com/vi/zeKE0NHUtUw/maxresdefault.jpg', 2008),
('Menu Theme', 'Super Smash Bros Ultimate', 'Various', '6znq-EYa8C0', 'https://img.youtube.com/vi/6znq-EYa8C0/maxresdefault.jpg', 2018),
('Lifelight', 'Super Smash Bros Ultimate', 'Abby Trott', 'EhgDibw7vB4', 'https://img.youtube.com/vi/EhgDibw7vB4/maxresdefault.jpg', 2018),
('Final Destination', 'Super Smash Bros Ultimate', 'Various', '04Wd9mE2nAI', 'https://img.youtube.com/vi/04Wd9mE2nAI/maxresdefault.jpg', 2018),
('Battlefield', 'Super Smash Bros Ultimate', 'Various', 'GflpseDXY-U', 'https://img.youtube.com/vi/GflpseDXY-U/maxresdefault.jpg', 2018),
('Menu Theme', 'Super Smash Bros 64', 'Hirokazu Ando', 'wn8-4vymRMU', 'https://img.youtube.com/vi/wn8-4vymRMU/maxresdefault.jpg', 1999),
('Menu Theme', 'Super Smash Bros for Wii U', 'Various', 'qDnaIfiH37w', 'https://img.youtube.com/vi/qDnaIfiH37w/maxresdefault.jpg', 2014),
('Fossil Falls', 'Super Mario Odyssey', 'Naoki Sakatoku', '8y2OPEShyrQ', 'https://img.youtube.com/vi/8y2OPEShyrQ/maxresdefault.jpg', 2017),
('Steam Gardens', 'Super Mario Odyssey', 'Naoki Sakatoku', '-rfoYSmx0rk', 'https://img.youtube.com/vi/-rfoYSmx0rk/maxresdefault.jpg', 2017),
('Big Blue', 'Mario Kart 8', 'Various', '16Zq8EMCdZ4', 'https://img.youtube.com/vi/16Zq8EMCdZ4/maxresdefault.jpg', 2014),
('Fever', 'Dr. Mario', 'Hirokazu Tanaka', 'aiuFBFPC7YQ', 'https://img.youtube.com/vi/aiuFBFPC7YQ/maxresdefault.jpg', 1990),
('Big Bowser Battle', 'Yoshi''s Island', 'Koji Kondo', 'GZ9VGiqcbDw', 'https://img.youtube.com/vi/GZ9VGiqcbDw/maxresdefault.jpg', 1995),
('Slider', 'Super Mario 64', 'Koji Kondo', 'w-OeUbJo1V4', 'https://img.youtube.com/vi/w-OeUbJo1V4/maxresdefault.jpg', 1996),
('Snowline Circuit', 'Mario Kart DS', 'Shinobu Tanaka', 'OieGlzEeUZk', 'https://img.youtube.com/vi/OieGlzEeUZk/maxresdefault.jpg', 2005);
